name: Build Runtime

on:
  push:
    branches:
      - main
      - main-*
      - develop
      - release/*
      - feature/*
      - ci/*
    tags:
      - v*
  pull_request:

permissions:
  contents: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Runtime
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Build Runtime
        run: |
          dotnet publish Runtime \
            --configuration Release \
            --runtime linux-x64 \
            --no-self-contained \
            --output out

      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v4
        if: "!startsWith(github.ref, 'refs/tags/')"
        with:
          name: dotnet-runtime
          path: out/Runtime

      - name: Set Tag Environment Variable
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Upload release file
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Release ${{ env.RELEASE_VERSION }}
          path: out/Runtime
